### ISSUE TITLE
Chatbot doesn't respond

### ISSUE THREAD

**Issue by stormanh** [SumitKanchan4/SPFx-QnA-ChatBot#1]
Hi Sumit.

I followed the instructions on your site: https://www.sharepointwidgets.com/2020/09/spfx-chat-bot-using-sharepoint.html but when I deploy the chatbot it doesn't respond back as shown in the image below.  Any ideas how to resolve this issue?

![image](https://user-images.githubusercontent.com/44712300/111238744-13fc6f80-85ce-11eb-8923-b077f6e9163a.png)

Here's the error in the console:
 (in promise) TypeError: Cannot read property 'length' of undefined
    at t.createHttpClientOptions (chat-bot-application-customizer_16cb3538219ec76457bfb7977dca62f2.js:1)
    at t.<anonymous> (chat-bot-application-customizer_16cb3538219ec76457bfb7977dca62f2.js:1)
    at chat-bot-application-customizer_16cb3538219ec76457bfb7977dca62f2.js:1
    at Object.next (chat-bot-application-customizer_16cb3538219ec76457bfb7977dca62f2.js:1)
    at chat-bot-application-customizer_16cb3538219ec76457bfb7977dca62f2.js:1
    at new Promise (<anonymous>)
    at Na (chat-bot-application-customizer_16cb3538219ec76457bfb7977dca62f2.js:1)
    at t.getAnswer (chat-bot-application-customizer_16cb3538219ec76457bfb7977dca62f2.js:1)
    at chat-bot-application-customizer_16cb3538219ec76457bfb7977dca62f2.js:1

Thanks,
stormanh

**Comment by SumitKanchan4** [comment]
Hi,

Sorry for late reply, can you check using fiddler or browser network logs...

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: stormanh ***@***.***>
Sent: Tuesday, March 16, 2021 6:08:11 AM
To: SumitKanchan4/SPFx-QnA-ChatBot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SumitKanchan4/SPFx-QnA-ChatBot] Chatbot doesn't respond (#1)


Hi Sumit.

I followed the instructions on your site: https://www.sharepointwidgets.com/2020/09/spfx-chat-bot-using-sharepoint.html but when I deploy the chatbot it doesn't respond back as shown in the image below. Any ideas how to resolve this issue?

[image]<https://user-images.githubusercontent.com/44712300/111238744-13fc6f80-85ce-11eb-8923-b077f6e9163a.png>

Thanks,
stormanh

**Comment by ghost** [comment]
Hi Sumit, 
Got exactly the same error as defined by stormanh. Any ideas? 
Thanks a lot.

**Comment by SumitKanchan4** [comment]
Hi, I have updated the code for handling the error, can you try once more and let's see where it is breaking. I have not updated the package, so try cloning the solution, update the configuration, and then deploying the solution
